config/routes.rb
Rails.application.routes.draw do
  resources :short_puts
  resources :bull_put_spreads
  devise_for :users

  root 'static_pages#home'

  get '/trades', to: 'static_pages#show_trades'
  get 'bps', to: 'bull_put_spreads#index'

  
  devise_scope :user do
    # register
    get 'signup', to: 'devise/registrations#new'
    # sessions
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end

end
 

app/models/bull_put_spread.rb
class BullPutSpread < ApplicationRecord
  belongs_to :user
  validates :strike, presence: true
  validates :asset, presence: true

  def dte 
    today = Date.today
    (expiration - today).to_i
  end

  def formatted_expiration
    expiration.strftime("%m-%d-%y") 
  end
end

app/controllers/bull_put_spreads_controller.rb
class BullPutSpreadsController < ApplicationController
  before_action :set_bull_put_spread, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /bull_put_spreads
  # GET /bull_put_spreads.json
  def index
    @bull_put_spreads = current_user.bull_put_spreads.all
  end

  # GET /bull_put_spreads/1
  # GET /bull_put_spreads/1.json
  def show
    @floors = [@bull_put_spread.floor1, @bull_put_spread.floor2, @bull_put_spread.strike]
    @floor_names = ["Floor 1", "Floor 2", "Strike"]
    @rut_price = 1526.48
  end

  # GET /bull_put_spreads/new
  def new
    @bull_put_spread = BullPutSpread.new
  end

  # GET /bull_put_spreads/1/edit
  def edit
  end

  # POST /bull_put_spreads
  # POST /bull_put_spreads.json
  def create
    @bull_put_spread = current_user.bull_put_spreads.build(bull_put_spread_params)

    if @bull_put_spread.save
      flash[:success] = "Saved!"
      redirect_to @bull_put_spread
    else
      render 'new'
    end
  end

  # PATCH/PUT /bull_put_spreads/1
  # PATCH/PUT /bull_put_spreads/1.json
  def update
    if @bull_put_spread.update(bull_put_spread_params)
      flash[:success] = "Trade updated"
      redirect_to @bull_put_spread
    else
      render 'edit'
    end
  end

  # DELETE /bull_put_spreads/1
  # DELETE /bull_put_spreads/1.json
  def destroy
    @bull_put_spread.destroy
    flash[:success] = "Trade deleted"
    redirect_to bull_put_spreads_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bull_put_spread
      @bull_put_spread = BullPutSpread.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bull_put_spread_params
      params.require(:bull_put_spread).permit(:floor1, :floor2, :strike, :expiration, :asset)
    end
end

app/helpers/bull_put_spreads_helper.rb
module BullPutSpreadsHelper

end

app/views/bull_put_spreads/_form.html.erb
<%= form_with(model: bull_put_spread, local: true) do |form| %>
  <% if bull_put_spread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bull_put_spread.errors.count, "error") %> prohibited this bull_put_spread from being saved:</h2>

      <ul>
        <% bull_put_spread.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="wrapper fadeInDown">
    <div id="formContent">

      <div class="fadeIn first">
        <h1 class="login">Bull Put Spread</h1>
      </div>

      <div class="field">
        <%= form.text_field :asset, class: "fadeIn second", id: "login", type: "text", placeholder: "Ticker"  %>
      </div>

      <div class="field">
        <%= form.text_field :floor1, class: "fadeIn third", id: "login", type: "text", placeholder: "Floor 1" %>
      </div>

      <div class="field">
        <%= form.text_field :floor2, class: "fadeIn fourth", id: "login", type: "text", placeholder: "Floor 2" %>
      </div>

      <div class="field">
        <%= form.text_field :strike, class: "fadeIn fifth", id: "login", type: "text", placeholder: "Strike" %>
      </div>

      <div class="field fadeIn sixth" type="text">
        <p class="expiration">Expiration:</p>
        <%= form.date_select :expiration, order: [:month, :day, :year], start_year: Date.today.year  %>
      </div>

      <div class="actions">
        <%= form.submit "Save", type: "submit", class: "fadeIn seventh btn btn-primary" %>
      </div>

    </div>
  </div>

<% end %>

app/views/bull_put_spreads/edit.html.erb
<% provide(:title, "Edit BPS") %>

<%= render 'form', bull_put_spread: @bull_put_spread %>

app/views/bull_put_spreads/index.html.erb
<% provide(:title, "BPS") %>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col text-center">
    <h1 class="bps">Bull Put Spreads</h1>
    
    <% if @bull_put_spreads.empty? %>
      <div class="row">
        <div class="col text-center">
          <p>You have no open BPS positions!</p>
          <%= link_to "Create BPS", new_bull_put_spread_path, class: "btn btn-primary" %>
        </div>
      </div>
    <% else %>
      <%= render 'shared/bps' %>
    <% end %>


  </div>
</div>

app/views/bull_put_spreads/new.html.erb
<% provide(:title, "New BPS") %>

<%= render 'form', bull_put_spread: @bull_put_spread %>

app/views/bull_put_spreads/show.html.erb
<p id="notice"><%= notice %></p>

<% title = @bull_put_spread.asset + " " + number_to_currency(@bull_put_spread.strike).to_s %>
<% provide(:title, title) %>

<div class="row">
  <div class="col-md-2 offset-md-4">
    <h5 class="stats"><b>Security:</b></h5>
    <h5 class="stats"><b>Current Price:</b></h5>
    <h5 class="stats"><b>Expiration Date:</b></h5>
    <h5 class="stats"><b>DTE:</b></h5>
  </div>
    <div class="col-md-2">
      <h5 class="stats"><%= @bull_put_spread.asset %></h5>
      <h5 class="stats"><%= number_to_currency(@rut_price) %></h5>
      <h5 class="stats"><%= @bull_put_spread.formatted_expiration %></h5>
      <h5 class="stats"><%= @bull_put_spread.dte %> <%= 'day'.pluralize(@bull_put_spread.dte.to_i) %></h5>
      <h5 class="stats">(<%= business_days_between(Date.today,@bull_put_spread.expiration) %> trading <%= 'day'.pluralize(@bull_put_spread.dte.to_i) %>)</h5>
  </div>
</div><br>

<div class="row">
  <div class="col text-center">
    <%= link_to "Edit", edit_bull_put_spread_path, class: "btn btn-primary cards" %>
    <%= link_to "Delete", bull_put_spread_path, class: "btn btn-danger cards", method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</div>

<% @floors.each_with_index do |f,i| %>
  <div class="floor">
    <% unless f.nil? %>
      <div class="col text-center"><%= @floor_names[i] %></div>
      <div class="row">
        <div class="col-md-6 text-right">
          <h1 class="floor"><%= number_to_currency(f) %></h1>
        </div>
        <div class="col-md-2 text-left my-auto">
          <p class="stats"><%= number_to_currency(f-@rut_price) %></p>
          <p class="stats"><%= (((f-@rut_price)/@rut_price)*100).round(2) %>%</p>
        </div>
        <div class="col-md-2 text-left my-auto">
          <p class="stats"><%= number_to_currency((f-@rut_price)/@bull_put_spread.dte) %>/day</p>
          <p class="stats-small">(approx. <%= (((f-@rut_price)/@rut_price)*100/@bull_put_spread.dte).round(2) %>%)</p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>