config/routes.rb
Rails.application.routes.draw do
  resources :short_puts
  resources :bull_put_spreads
  devise_for :users

  root 'static_pages#home'

  get '/trades', to: 'static_pages#show_trades'
  get 'bps', to: 'bull_put_spreads#index'

  
  devise_scope :user do
    # register
    get 'signup', to: 'devise/registrations#new'
    # sessions
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end

end
 

app/models/short_put.rb
class ShortPut < ApplicationRecord
  belongs_to :user

  def dte 
    today = Date.today
    (expiration - today).to_i
  end

  def formatted_expiration
    expiration.strftime("%m-%d-%y") 
  end
end

app/controllers/short_puts_controller.rb
class ShortPutsController < ApplicationController
  before_action :set_short_put, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /short_puts
  # GET /short_puts.json
  def index
    @short_puts = current_user.short_puts.all 
  end

  # GET /short_puts/1
  # GET /short_puts/1.json
  def show
    @floors = [@short_put.floor1, @short_put.floor2, @short_put.strike]
    @floor_names = ["Floor 1", "Floor 2", "Strike"]
    if @short_put.asset == "FIVE"
      @price = 125
    else
      @price = 29     # SKX
    end
  end

  # GET /short_puts/new
  def new
    @short_put = ShortPut.new
  end

  # GET /short_puts/1/edit
  def edit
  end

  # POST /short_puts
  # POST /short_puts.json
  def create
    @short_put = current_user.short_puts.build(short_put_params)

    if @short_put.save
      flash[:success] = "Saved!"
      redirect_to @short_put
    else
      render 'new'
    end
  end

  # PATCH/PUT /short_puts/1
  # PATCH/PUT /short_puts/1.json
  def update
    if @short_put.update(short_put_params)
      flash[:success] = "Trade updated!"
      redirect_to @short_put
    end
  end

  # DELETE /short_puts/1
  # DELETE /short_puts/1.json
  def destroy
    @short_put.destroy
    flash[:success] = "Trade deleted!"
    redirect_to short_puts_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_short_put
      @short_put = ShortPut.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def short_put_params
      params.require(:short_put).permit(:floor1, :floor2, :strike, :expiration, :asset)
    end
end

app/helpers/short_puts_helper.rb
module ShortPutsHelper
end

app/views/short_puts/_form.html.erb
<%= form_with(model: short_put, local: true) do |form| %>
  <% if short_put.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(short_put.errors.count, "error") %> prohibited this short_put from being saved:</h2>

      <ul>
        <% short_put.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="wrapper fadeInDown">
    <div id="formContent">

      <div class="fadeIn first">
        <h1 class="login">Short Put</h1>
      </div>

      <div class="field">
        <%= form.text_field :asset, class: "fadeIn second", id: "login", type: "text", placeholder: "Ticker"  %>
      </div>

      <div class="field">
        <%= form.text_field :floor1, class: "fadeIn third", id: "login", type: "text", placeholder: "Floor 1" %>
      </div>

      <div class="field">
        <%= form.text_field :floor2, class: "fadeIn fourth", id: "login", type: "text", placeholder: "Floor 2" %>
      </div>

      <div class="field">
        <%= form.text_field :strike, class: "fadeIn fifth", id: "login", type: "text", placeholder: "Strike" %>
      </div>

      <div class="field fadeIn sixth" type="text">
        <p class="expiration">Expiration:</p>
        <%= form.date_select :expiration, order: [:month, :day, :year], start_year: Date.today.year  %>
      </div>

      <div class="actions">
        <%= form.submit "Save", type: "submit", class: "fadeIn seventh btn btn-primary" %>
      </div>

    </div>
  </div>

<% end %>

app/views/short_puts/edit.html.erb
<% provide(:titel, "Edit Short Put") %>

<%= render 'form', short_put: @short_put %>

app/views/short_puts/index.html.erb
<% provide(:title, "Short Puts") %>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col text-center">
    <h1 class="bps">Short Puts</h1>
    
    <% if @short_puts.empty? %>
      <div class="row">
        <div class="col text-center">
          <p>You have no open short put positions!</p>
          <%= link_to "Create Short Put", new_short_put_path, class: "btn btn-primary" %>
        </div>
      </div>
    <% else %>
      <%= render 'shared/shortput' %>
    <% end %>


  </div>
</div>

app/views/short_puts/new.html.erb
<% provide(:title, "New Short Put") %>

<%= render 'form', short_put: @short_put %>

app/views/short_puts/show.html.erb
<p id="notice"><%= notice %></p>

<% title = @short_put.asset + " " + number_to_currency(@short_put.strike).to_s %>
<% provide(:title, title) %>

<div class="row">
  <div class="col-md-2 offset-md-4">
    <h5 class="stats"><b>Security:</b></h5>
    <h5 class="stats"><b>Current Price:</b></h5>
    <h5 class="stats"><b>Expiration Date:</b></h5>
    <h5 class="stats"><b>DTE:</b></h5>
  </div>
    <div class="col-md-2">
      <h5 class="stats"><%= @short_put.asset %></h5>
      <h5 class="stats"><%= number_to_currency(@price) %></h5>
      <h5 class="stats"><%= @short_put.formatted_expiration %></h5>
      <h5 class="stats"><%= @short_put.dte %> <%= 'day'.pluralize(@short_put.dte.to_i) %></h5>
      <h5 class="stats">(<%= business_days_between(Date.today,@short_put.expiration) %> trading <%= 'day'.pluralize(@short_put.dte.to_i) %>)</h5>
  </div>
</div><br>

<div class="row">
  <div class="col text-center">
    <%= link_to "Edit", edit_short_put_path, class: "btn btn-primary cards" %>
    <%= link_to "Delete", short_put_path, class: "btn btn-danger cards", method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</div>

<% @floors.each_with_index do |f,i| %>
  <div class="floor">
    <% unless f.nil? %>
      <div class="col text-center"><%= @floor_names[i] %></div>
      <div class="row">
        <div class="col-md-6 text-right">
          <h1 class="floor"><%= number_to_currency(f) %></h1>
        </div>
        <div class="col-md-2 text-left my-auto">
          <p class="stats"><%= number_to_currency(f-@price) %></p>
          <p class="stats"><%= (((f-@price)/@price)*100).round(2) %>%</p>
        </div>
        <div class="col-md-2 text-left my-auto">
          <p class="stats"><%= number_to_currency((f-@price)/@short_put.dte) %>/day</p>
          <p class="stats-small">(approx. <%= (((f-@price)/@price)*100/@short_put.dte).round(2) %>%)</p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>